#! /usr/bin/env bash

(time smack --float --unroll 1 --integer-encoding bit-vector --verifier corral --entry-points musl_smack -- nextafter.rs nextafter.c) > cms.txt 2>&1 &
(time smack --float --unroll 1 --integer-encoding bit-vector --verifier corral --entry-points rust_smack -- nextafter.rs nextafter.c) > crs.txt 2>&1 &
(time smack --float --unroll 1 --integer-encoding bit-vector --verifier corral --entry-points musl_rust -- nextafter.rs nextafter.c) > cmr.txt 2>&1 &
(time smack --float --unroll 1 --integer-encoding bit-vector --verifier boogie --entry-points musl_smack -- nextafter.rs nextafter.c) > bms.txt 2>&1 &
(time smack --float --unroll 1 --integer-encoding bit-vector --verifier boogie --entry-points rust_smack -- nextafter.rs nextafter.c) > brs.txt 2>&1 &
(time smack --float --unroll 1 --integer-encoding bit-vector --verifier boogie --entry-points musl_rust -- nextafter.rs nextafter.c) > bmr.txt 2>&1 &

