#! /usr/bin/env bash

(hyperfine --runs 5 --ignore-failure 'smack --float --unroll 1 --integer-encoding bit-vector --verifier corral --entry-points musl_smack -- fmaxf.rs fmaxf.c') > cms.txt 2>&1 &
(hyperfine --runs 5 --ignore-failure 'smack --float --unroll 1 --integer-encoding bit-vector --verifier corral --entry-points rust_smack -- fmaxf.rs fmaxf.c') > crs.txt 2>&1 &
(hyperfine --runs 5 --ignore-failure 'smack --float --unroll 1 --integer-encoding bit-vector --verifier corral --entry-points musl_rust -- fmaxf.rs fmaxf.c') > cmr.txt 2>&1 &
(hyperfine --runs 5 --ignore-failure 'smack --float --unroll 1 --integer-encoding bit-vector --verifier boogie --entry-points musl_smack -- fmaxf.rs fmaxf.c') > bms.txt 2>&1 &
(hyperfine --runs 5 --ignore-failure 'smack --float --unroll 1 --integer-encoding bit-vector --verifier boogie --entry-points rust_smack -- fmaxf.rs fmaxf.c') > brs.txt 2>&1 &
(hyperfine --runs 5 --ignore-failure 'smack --float --unroll 1 --integer-encoding bit-vector --verifier boogie --entry-points musl_rust -- fmaxf.rs fmaxf.c') > bmr.txt 2>&1 &

