#! /usr/bin/env bash

(time smack --float --unroll 1 --integer-encoding bit-vector --verifier corral --entry-points musl_smack -- floor.rs floor.c) > cms.txt 2>&1 &
(time smack --float --unroll 1 --integer-encoding bit-vector --verifier corral --entry-points rust_smack -- floor.rs floor.c) > crs.txt 2>&1 &
(time smack --float --unroll 1 --integer-encoding bit-vector --verifier corral --entry-points musl_rust -- floor.rs floor.c) > cmr.txt 2>&1 &
(time smack --float --unroll 1 --integer-encoding bit-vector --verifier boogie --entry-points musl_smack -- floor.rs floor.c) > bms.txt 2>&1 &
(time smack --float --unroll 1 --integer-encoding bit-vector --verifier boogie --entry-points rust_smack -- floor.rs floor.c) > brs.txt 2>&1 &
(time smack --float --unroll 1 --integer-encoding bit-vector --verifier boogie --entry-points musl_rust -- floor.rs floor.c) > bmr.txt 2>&1 &

