#! /usr/bin/env bash

# (time smack --float --unroll 1 --integer-encoding bit-vector --verifier corral --entry-points musl_smack -- round.rs round.c) > cms.txt 2>&1 &
# (time smack --float --unroll 1 --integer-encoding bit-vector --verifier corral --entry-points rust_smack -- round.rs round.c) > crs.txt 2>&1 &
# (time smack --float --unroll 1 --integer-encoding bit-vector --verifier corral --entry-points musl_rust -- round.rs round.c) > cmr.txt 2>&1 &
# (time smack --float --unroll 1 --integer-encoding bit-vector --verifier boogie --entry-points musl_smack -- round.rs round.c) > bms.txt 2>&1 &
# (time smack --float --unroll 1 --integer-encoding bit-vector --verifier boogie --entry-points rust_smack -- round.rs round.c) > brs.txt 2>&1 &
# (time smack --float --unroll 1 --integer-encoding bit-vector --verifier boogie --entry-points musl_rust -- round.rs round.c) > bmr.txt 2>&1 &

(time smack --float --unroll 1 --integer-encoding bit-vector --verifier corral --entry-points musl_smack -- round2.rs round.c) > cms2.txt 2>&1 &
(time smack --float --unroll 1 --integer-encoding bit-vector --verifier corral --entry-points rust_smack -- round2.rs round.c) > crs2.txt 2>&1 &
(time smack --float --unroll 1 --integer-encoding bit-vector --verifier corral --entry-points musl_rust -- round2.rs round.c) > cmr2.txt 2>&1 &
(time smack --float --unroll 1 --integer-encoding bit-vector --verifier boogie --entry-points musl_smack -- round2.rs round.c) > bms2.txt 2>&1 &
(time smack --float --unroll 1 --integer-encoding bit-vector --verifier boogie --entry-points rust_smack -- round2.rs round.c) > brs2.txt 2>&1 &
(time smack --float --unroll 1 --integer-encoding bit-vector --verifier boogie --entry-points musl_rust -- round2.rs round.c) > bmr2.txt 2>&1 &

