#! /usr/bin/env bash

(time smack --float --unroll 1 --integer-encoding bit-vector --verifier corral --entry-points musl_smack -- copysignf.rs copysignf.c) >> cms.txt 2>&1 &
(time smack --float --unroll 1 --integer-encoding bit-vector --verifier corral --entry-points rust_smack -- copysignf.rs copysignf.c) >> crs.txt 2>&1 &
(time smack --float --unroll 1 --integer-encoding bit-vector --verifier corral --entry-points musl_rust -- copysignf.rs copysignf.c) >> cmr.txt 2>&1 &
(time smack --float --unroll 1 --integer-encoding bit-vector --verifier boogie --entry-points musl_smack -- copysignf.rs copysignf.c) >> bms.txt 2>&1 &
(time smack --float --unroll 1 --integer-encoding bit-vector --verifier boogie --entry-points rust_smack -- copysignf.rs copysignf.c) >> brs.txt 2>&1 &
(time smack --float --unroll 1 --integer-encoding bit-vector --verifier boogie --entry-points musl_rust -- copysignf.rs copysignf.c) >> bmr.txt 2>&1 &

