#! /usr/bin/env bash

(time smack --float --integer-encoding bit-vector --verifier corral --entry-points musl_smack -- truncf.rs truncf.c) >> cms.txt 2>&1 &
(time smack --float --integer-encoding bit-vector --verifier corral --entry-points rust_smack -- truncf.rs truncf.c) >> crs.txt 2>&1 &
(time smack --float --integer-encoding bit-vector --verifier corral --entry-points musl_rust -- truncf.rs truncf.c) >> cmr.txt 2>&1 &
(time smack --float --integer-encoding bit-vector --verifier boogie --entry-points musl_smack -- truncf.rs truncf.c) >> bms.txt 2>&1 &
(time smack --float --integer-encoding bit-vector --verifier boogie --entry-points rust_smack -- truncf.rs truncf.c) >> brs.txt 2>&1 &
(time smack --float --integer-encoding bit-vector --verifier boogie --entry-points musl_rust -- truncf.rs truncf.c) >> bmr.txt 2>&1 &

